CREATE_SCHEMA_USER = """
CREATE SCHEMA IF NOT EXISTS "user";
"""

CREATE_SCHEMA_WORKSHOP = """
CREATE SCHEMA IF NOT EXISTS workshop;
"""

CREATE_SCHEMA_LANDING = """
CREATE SCHEMA IF NOT EXISTS landing;
"""


CREATE_TABLE_EMPLOYEES = """
CREATE TABLE IF NOT EXISTS "user".employees (
    id SERIAL PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active BOOLEAN DEFAULT true,
    password_hash VARCHAR(255) NOT NULL,
    CONSTRAINT employees_email_unique UNIQUE (email)
);
"""

CREATE_SCHEMAS = [CREATE_SCHEMA_USER]

CREATE_TABLES = [CREATE_TABLE_EMPLOYEES]